rvm:
  - 2.6.6

language: ruby

cache: bundler

services:
  - mongodb
  - xvfb

addons:
  firefox: 54.0

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
